version: '3'

services:

  node-app:
    build:
      context: .
      dockerfile: node.dockerfile
    ports:
      - "8080:8080"
    depends_on: 
      - mongodb
    links:  
      - mongodb 
    environment:
      - SERVICE_PORTS=8080
      
  mongodb:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

  loadbalancer:
    image: dockercloud/haproxy:latest
    depends_on:
      - node-app
    environment:
      - BALANCE=leastconn
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
    links:  
      - node-app




